#!/usr/bin/env bash
# displays listening ports: listening sockets, PID and name of the program to which each socket belongs
echo "Active Internet connections (only servers)"
sudo netstat -tulnp
echo "Active UNIX domain sockets (only servers)"
sudo netstat -lxnp 